# Generated by Django 2.1 on 2023-06-15 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pcat', models.CharField(max_length=50)),
                ('pcost', models.CharField(max_length=50)),
                ('pquality', models.CharField(max_length=50)),
                ('pdec', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cemail', models.CharField(max_length=50)),
                ('cpassword', models.CharField(max_length=50)),
                ('cmno', models.CharField(max_length=50)),
                ('cadd', models.CharField(max_length=50)),
                ('cpin', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Register'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.Products'),
        ),
    ]
